import type { StoryItem } from "@/components/StoryCard";

export const MOCK_STORIES: StoryItem[] = [
  // ── Russian-language stories ────────────────────────────────────────────────
  {
    id: 1,
    title: "Хроники Тёмного Леса",
    author: "Артём Белов",
    genres: ["fantasy", "adventure"],
    language: ["ru"],
    year: 2023,
    country: "Russia",
    status: "ongoing",
    pages: 120,
    chapters: 18,
    rating: 4.8,
    description:
      "Молодой охотник обнаруживает в глубине проклятого леса древний артефакт, пробуждающий силы, которые не должны были вернуться.",
  },
  {
    id: 2,
    title: "Город Снов",
    author: "Мария Соколова",
    genres: ["mystery", "thriller"],
    language: ["ru"],
    year: 2022,
    country: "Kazakhstan",
    status: "completed",
    pages: 85,
    chapters: 34,
    rating: 4.5,
    description:
      "Детектив расследует серию странных исчезновений, которые связаны с загадочным городом, существующим только во снах.",
  },
  {
    id: 3,
    title: "Механический Рыцарь",
    author: "Дмитрий Орлов",
    genres: ["steampunk", "scifi"],
    language: ["ru"],
    year: 2024,
    country: "Russia",
    status: "ongoing",
    pages: 200,
    chapters: 52,
    rating: 4.2,
    description:
      "В мире пара и шестерёнок одинокий изобретатель создаёт боевого голема, чтобы защитить свой город от надвигающейся армии.",
  },
  {
    id: 4,
    title: "Алая Луна",
    author: "Наталья Ким",
    genres: ["romance", "fantasy"],
    language: ["ru"],
    year: 2023,
    country: "Kyrgyzstan",
    status: "completed",
    pages: 65,
    chapters: 29,
    rating: 4.6,
    description:
      "Под кровавой луной двое врагов вынуждены объединиться, чтобы выжить, и постепенно открывают в себе чувства сильнее ненависти.",
  },
  {
    id: 5,
    title: "Звёздный Странник",
    author: "Игорь Зайцев",
    genres: ["scifi", "adventure"],
    language: ["ru"],
    year: 2024,
    country: "Russia",
    status: "ongoing",
    pages: 350,
    chapters: 11,
    rating: 4.9,
    description:
      "Капитан заброшенного звездолёта получает сигнал с планеты, которой нет ни на одной карте. Это может быть спасение — или ловушка.",
  },
  {
    id: 6,
    title: "Тайны Подземелья",
    author: "Ольга Федорова",
    genres: ["adventure", "mystery"],
    language: ["ru"],
    year: 2021,
    country: "Uzbekistan",
    status: "completed",
    pages: 145,
    chapters: 7,
    rating: 4.3,
    description:
      "Группа студентов-археологов проникает в запретные катакомбы под Москвой и сталкивается с историей, которую власти хотели скрыть.",
  },
  {
    id: 7,
    title: "Сердце Дракона",
    author: "Павел Морозов",
    genres: ["fantasy", "romance"],
    language: ["ru"],
    year: 2024,
    country: "Kazakhstan",
    status: "ongoing",
    pages: 280,
    chapters: 61,
    rating: 4.7,
    description:
      "Принцесса, проклятая с рождения, отправляется на край света, чтобы найти последнего дракона — единственного, кто может её исцелить.",
  },
  {
    id: 8,
    title: "Последний Самурай",
    author: "Анна Петрова",
    genres: ["historical", "action"],
    language: ["ru"],
    year: 2022,
    country: "Russia",
    status: "completed",
    pages: 420,
    chapters: 23,
    rating: 4.4,
    description:
      "Эпическая история воина, который отказывается принять новый порядок и в одиночку бросает вызов целой империи, чтобы сохранить честь.",
  },

  // ── Kyrgyz-language stories ─────────────────────────────────────────────────
  {
    id: 9,
    title: "Манас баатыр",
    author: "Тилек Усупов",
    genres: ["historical", "adventure"],
    language: ["ky"],
    year: 2023,
    country: "Kyrgyzstan",
    status: "ongoing",
    pages: 210,
    chapters: 28,
    rating: 4.9,
    description:
      "Байыркы Кыргыз жеринде баатыр Манастын мираскорлору жаңы коркунучтарга каршы чыгышат. Эпостун заманбап интерпретациясы.",
  },
  {
    id: 10,
    title: "Ала-Тоонун сыры",
    author: "Айгүл Сейткали",
    genres: ["mystery", "adventure"],
    language: ["ky"],
    year: 2022,
    country: "Kyrgyzstan",
    status: "completed",
    pages: 95,
    chapters: 15,
    rating: 4.5,
    description:
      "Жаш журналист Ала-Тоо тоолорунда жок болгон экспедиция жөнүндө сырды чечмелөөгө аракет кылат.",
  },
  {
    id: 11,
    title: "Бишкектин жүрөгү",
    author: "Нуржан Осмонов",
    genres: ["romance", "scifi"],
    language: ["ky"],
    year: 2024,
    country: "Kyrgyzstan",
    status: "ongoing",
    pages: 135,
    chapters: 19,
    rating: 4.6,
    description:
      "Келечек Бишкекте эки жаш программист робот менен адамдын ортосундагы чекти сындырган программаны иштеп чыгышат.",
  },
  {
    id: 12,
    title: "Комуздун үнү",
    author: "Зарина Бекова",
    genres: ["historical", "romance"],
    language: ["ky"],
    year: 2021,
    country: "Kyrgyzstan",
    status: "completed",
    pages: 175,
    chapters: 24,
    rating: 4.7,
    description:
      "XIX кылымдагы Кыргыз жеринде акын кыз өз элинин боштондугу үчүн комузунун күчү менен күрөшөт.",
  },

  // ── Bilingual story ─────────────────────────────────────────────────────────
  {
    id: 13,
    title: "Эки жол / Два пути",
    author: "Гүлзат Асанова",
    genres: ["fantasy", "adventure"],
    language: ["ru", "ky"],
    year: 2024,
    country: "Kyrgyzstan",
    status: "ongoing",
    pages: 250,
    chapters: 33,
    rating: 4.8,
    description:
      "Согуш тарабынан ажыраган эки бир тууган жөнүндө экитилдүү роман. / Билингвальный роман о двух братьях, разделённых войной — один пишет по-русски, другой по-кыргызски.",
  },
];
