import type { StoryItem } from "@/components/StoryCard";

export const MOCK_FANFICS: StoryItem[] = [
  {
    id: 101,
    title: "Наследие Стального Алхимика",
    author: "Элина Март",
    genres: ["fantasy", "adventure"],
    language: ["ru"],
    year: 2023,
    country: "Russia",
    status: "ongoing",
    pages: 95,
    chapters: 22,
    rating: 4.7,
    description:
      "Что если бы Эдвард Элрик обнаружил камень философов не там, где ожидал? Альтернативная история, исследующая последствия иного пути.",
  },
  {
    id: 102,
    title: "Тени Аренды",
    author: "Диас Сейткали",
    genres: ["action", "drama"],
    language: ["ru"],
    year: 2022,
    country: "Kazakhstan",
    status: "completed",
    pages: 60,
    chapters: 15,
    rating: 4.4,
    description:
      "Спин-офф о малоизвестном персонаже книжной вселенной, чья история осталась за кадром оригинала.",
  },
  {
    id: 103,
    title: "Другой Горизонт",
    author: "Айгуль Токтосунова",
    genres: ["romance", "adventure"],
    language: ["ky"],
    year: 2024,
    country: "Kyrgyzstan",
    status: "ongoing",
    pages: 45,
    chapters: 11,
    rating: 4.6,
    description:
      "Фанфик по мотивам знаменитой кыргызской приключенческой серии — о том, как могло бы всё сложиться иначе.",
  },
  {
    id: 104,
    title: "Созвездие Вороны",
    author: "Максим Дорофеев",
    genres: ["mystery", "thriller"],
    language: ["ru"],
    year: 2023,
    country: "Russia",
    status: "completed",
    pages: 130,
    chapters: 30,
    rating: 4.8,
    description:
      "Детективный кроссовер двух популярных серий. Когда следователи из разных вселенных встречаются, правда оказывается сложнее.",
  },
  {
    id: 105,
    title: "За гранью финала",
    author: "Сабина Уразова",
    genres: ["drama", "romance"],
    language: ["ru"],
    year: 2024,
    country: "Uzbekistan",
    status: "ongoing",
    pages: 75,
    chapters: 18,
    rating: 4.3,
    description:
      "Продолжение истории, которая, по мнению читателей, закончилась слишком рано. Автор даёт персонажам второй шанс.",
  },
  {
    id: 106,
    title: "Параллельный мир",
    author: "Тимур Ахмедов",
    genres: ["scifi", "adventure"],
    language: ["ru"],
    year: 2022,
    country: "Uzbekistan",
    status: "completed",
    pages: 110,
    chapters: 25,
    rating: 4.5,
    description:
      "Что если бы события любимой фантастической саги разворачивались в другом измерении? Смелый AU-эксперимент.",
  },
  {
    id: 107,
    title: "Голос из прошлого",
    author: "Нурзат Эргешова",
    genres: ["historical", "drama"],
    language: ["ky"],
    year: 2023,
    country: "Kyrgyzstan",
    status: "ongoing",
    pages: 88,
    chapters: 20,
    rating: 4.2,
    description:
      "Фанфик о предках главных героев популярного эпика — как начиналась история, ставшая легендой.",
  },
  {
    id: 108,
    title: "Запрещённая магия",
    author: "Ольга Левина",
    genres: ["fantasy", "horror"],
    language: ["ru"],
    year: 2024,
    country: "Russia",
    status: "ongoing",
    pages: 165,
    chapters: 38,
    rating: 4.9,
    description:
      "Мрачный AU, в котором второстепенный злодей оригинального произведения становится протагонистом и ищет путь к искуплению.",
  },
];
