import type { StoryItem } from "@/components/StoryCard";

export const MOCK_COMICS: StoryItem[] = [
  {
    id: 201,
    title: "Стальной Дозор",
    author: "Роман Власов",
    genres: ["action", "scifi"],
    language: ["ru"],
    year: 2023,
    country: "Russia",
    status: "ongoing",
    pages: 180,
    chapters: 24,
    rating: 4.7,
    description:
      "В постапокалиптическом мире небольшой отряд защитников последнего города сражается с механическими чудовищами, порождёнными ИИ.",
  },
  {
    id: 202,
    title: "Девять Небес",
    author: "Айдана Бекова",
    genres: ["fantasy", "adventure"],
    language: ["ky"],
    year: 2024,
    country: "Kyrgyzstan",
    status: "ongoing",
    pages: 96,
    chapters: 12,
    rating: 4.9,
    description:
      "Юная шаманка поднимается сквозь девять небесных уровней кыргызской мифологии, чтобы вернуть украденную душу своего брата.",
  },
  {
    id: 203,
    title: "Ночной Базар",
    author: "Карим Юсупов",
    genres: ["mystery", "comedy"],
    language: ["ru"],
    year: 2022,
    country: "Uzbekistan",
    status: "completed",
    pages: 120,
    chapters: 16,
    rating: 4.5,
    description:
      "Детектив-растяпа расследует кражи на загадочном ночном рынке, где каждый торговец скрывает сверхъестественный секрет.",
  },
  {
    id: 204,
    title: "Хроники Арала",
    author: "Дина Сейткали",
    genres: ["drama", "historical"],
    language: ["ru"],
    year: 2023,
    country: "Kazakhstan",
    status: "completed",
    pages: 200,
    chapters: 28,
    rating: 4.8,
    description:
      "Графическая история нескольких поколений семьи рыбаков, наблюдающих высыхание Аральского моря.",
  },
  {
    id: 205,
    title: "Кибер Алматы",
    author: "Жансая Омарова",
    genres: ["scifi", "thriller"],
    language: ["ru"],
    year: 2024,
    country: "Kazakhstan",
    status: "ongoing",
    pages: 140,
    chapters: 18,
    rating: 4.6,
    description:
      "В неоновых трущобах будущего Алматы хакер случайно взламывает систему, контролирующую сознание миллионов граждан.",
  },
  {
    id: 206,
    title: "Духи Тянь-Шаня",
    author: "Нурбек Токтогулов",
    genres: ["fantasy", "horror"],
    language: ["ky"],
    year: 2023,
    country: "Kyrgyzstan",
    status: "ongoing",
    pages: 88,
    chapters: 11,
    rating: 4.4,
    description:
      "Горный проводник встречает духов, охраняющих древние перевалы, и вынужден заключить с ними опасный договор.",
  },
  {
    id: 207,
    title: "Красный Песок",
    author: "Фируза Назарова",
    genres: ["adventure", "romance"],
    language: ["ru"],
    year: 2022,
    country: "Tajikistan",
    status: "completed",
    pages: 160,
    chapters: 20,
    rating: 4.3,
    description:
      "Двое археологов находят в пустыне артефакт, переносящий их в древнюю цивилизацию, и влюбляются в эпоху прошлого.",
  },
  {
    id: 208,
    title: "Мегаполис Z",
    author: "Антон Крылов",
    genres: ["action", "dystopia"],
    language: ["ru"],
    year: 2024,
    country: "Russia",
    status: "ongoing",
    pages: 220,
    chapters: 30,
    rating: 4.7,
    description:
      "Одиночка-курьер в тоталитарном мегаполисе случайно становится лицом подпольного сопротивления.",
  },
];
