export type AuthorItem = {
  id: number;
  username: string;
  displayName: string;
  subscribers: number;
  country: string;
  genres: string[];
  avatarColor: string;
  weeklyGain: number;
  totalReads: number;
  memberSince: string;
};

export const MOCK_AUTHORS: AuthorItem[] = [
  {
    id: 1,
    username: "artem_belov",
    displayName: "Артём Белов",
    subscribers: 14820,
    country: "Russia",
    genres: ["fantasy", "adventure"],
    avatarColor: "#7c3aed",
    weeklyGain: 340,
    totalReads: 98400,
    memberSince: "Mar 2022",
  },
  {
    id: 2,
    username: "maria_sokolova",
    displayName: "Мария Соколова",
    subscribers: 11540,
    country: "Kazakhstan",
    genres: ["mystery", "thriller"],
    avatarColor: "#db2777",
    weeklyGain: 510,
    totalReads: 74200,
    memberSince: "Jun 2021",
  },
  {
    id: 3,
    username: "dmitry_orlov",
    displayName: "Дмитрий Орлов",
    subscribers: 9870,
    country: "Russia",
    genres: ["steampunk", "scifi"],
    avatarColor: "#0891b2",
    weeklyGain: 190,
    totalReads: 61500,
    memberSince: "Jan 2023",
  },
  {
    id: 4,
    username: "natalya_kim",
    displayName: "Наталья Ким",
    subscribers: 8300,
    country: "Kyrgyzstan",
    genres: ["romance", "fantasy"],
    avatarColor: "#d97706",
    weeklyGain: 620,
    totalReads: 53800,
    memberSince: "Sep 2022",
  },
  {
    id: 5,
    username: "igor_zaitsev",
    displayName: "Игорь Зайцев",
    subscribers: 22100,
    country: "Russia",
    genres: ["scifi", "adventure"],
    avatarColor: "#059669",
    weeklyGain: 280,
    totalReads: 142000,
    memberSince: "Nov 2020",
  },
  {
    id: 6,
    username: "aydana_bekova",
    displayName: "Айдана Бекова",
    subscribers: 7650,
    country: "Kyrgyzstan",
    genres: ["fantasy", "adventure"],
    avatarColor: "#e11d48",
    weeklyGain: 870,
    totalReads: 48300,
    memberSince: "Apr 2023",
  },
  {
    id: 7,
    username: "karim_yusupov",
    displayName: "Карим Юсупов",
    subscribers: 6200,
    country: "Uzbekistan",
    genres: ["mystery", "comedy"],
    avatarColor: "#7c3aed",
    weeklyGain: 150,
    totalReads: 39100,
    memberSince: "Jul 2023",
  },
  {
    id: 8,
    username: "dina_seitkali",
    displayName: "Дина Сейткали",
    subscribers: 18900,
    country: "Kazakhstan",
    genres: ["drama", "historical"],
    avatarColor: "#0369a1",
    weeklyGain: 440,
    totalReads: 121600,
    memberSince: "Feb 2021",
  },
  {
    id: 9,
    username: "zhansaya_omarova",
    displayName: "Жансая Омарова",
    subscribers: 13400,
    country: "Kazakhstan",
    genres: ["scifi", "thriller"],
    avatarColor: "#be185d",
    weeklyGain: 760,
    totalReads: 87900,
    memberSince: "Aug 2022",
  },
  {
    id: 10,
    username: "nurbek_toktogul",
    displayName: "Нурбек Токтогулов",
    subscribers: 5900,
    country: "Kyrgyzstan",
    genres: ["fantasy", "horror"],
    avatarColor: "#065f46",
    weeklyGain: 95,
    totalReads: 34700,
    memberSince: "Oct 2023",
  },
  {
    id: 11,
    username: "anton_krylov",
    displayName: "Антон Крылов",
    subscribers: 17200,
    country: "Russia",
    genres: ["action", "dystopia"],
    avatarColor: "#92400e",
    weeklyGain: 530,
    totalReads: 109400,
    memberSince: "May 2021",
  },
  {
    id: 12,
    username: "firuza_nazarova",
    displayName: "Фируза Назарова",
    subscribers: 4100,
    country: "Tajikistan",
    genres: ["adventure", "romance"],
    avatarColor: "#6d28d9",
    weeklyGain: 210,
    totalReads: 24800,
    memberSince: "Dec 2023",
  },
];
